trigger:
  - main
  - develop

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildDocker
    steps:
    - task: Docker@2
      displayName: Docker Login
      inputs:
        containerRegistry: 'DockerHub'
        command: 'login'
        addPipelineData: false
        addBaseImageData: false

    - script: ./build.sh
      displayName: Build & Push Image
      # buildx writes to stderr
      # failOnStderr: true